@GamesTradeIn.API_HostAddress = http://localhost:5000

POST http://localhost:5153/api/users
Content-Type: application/json

{
    "name" : "Vincially",
    "email" : "vincially@hotmail.com",
    "balance": 20000,
    "wishlist": [
    {
        "title": "Clair Obscur:Expedition 33",
        "platform": "Steam"
    },
    {
        "title": "Persona 4:Revival",
        "platform": "Steam"
    }
  ]
}

###

GET http://localhost:5000/api/users/111
Accept: application/json

###
